pipeline:
  create_cluster:
    image: banzaicloud/ci-pipeline-client:0.8
    cluster:
      name: dmazhukovkk8p
      location: ""
      cloud: google
      secretId: ""
      secretName: ""
      profileName: ""
      postHooks: {}
      properties: null
    action: EnsureCluster
  test:
    image: node:10-slim
    commands:
    - npm ci
    - npm test
  build_image:
    dockerfile: Dockerfile
    image: plugins/docker
    repo: '{{ .CICD_REPO }}'
    secretFrom:
      DOCKER_PASSWORD:
        keyRef: password
        name: docker-hub
      DOCKER_USERNAME:
        keyRef: username
        name: docker-hub
    tags: '{{ trunc 7 .CICD_COMMIT_SHA }}'
  package_application:
    when:
      branch:
        include:
        - master
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm init -c
    - helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
    - helm package ./.banzaicloud/charts/spotguide-nodejs-mongodb
  install_mongodb_user_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      sourceSecretName: nodejs-mongodb-mongodb
      spec:
      - name: mongodb-username
        source: username
      - name: mongodb-password
        source: password
    image: banzaicloud/ci-pipeline-client:0.8
    when:
      branch:
        include:
        - master
  install_mongodb_root_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      sourceSecretName: nodejs-mongodb-mongodb-root
      spec:
      - name: mongodb-root-password
        source: password
    image: banzaicloud/ci-pipeline-client:0.8
    when:
      branch:
        include:
        - master
  install_mongodb_replica_set_key_secret:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-mongodb'
      namespace: default
      sourceSecretName: nodejs-mongodb-mongodb-replicaset-key
      spec:
      - name: mongodb-replica-set-key
        source: password
    image: banzaicloud/ci-pipeline-client:0.8
    when:
      branch:
        include:
        - master
  deploy_application:
    action: EnsureDeployment
    deployment:
      name: ./spotguide-nodejs-mongodb-1.0.0.tgz
      releaseName: '{{ .CICD_REPO_NAME }}'
      reuseValues: true
      timeout: 900
      values:
        application:
          deployment:
            image:
              pullPolicy: Always
              repository: '{{ .CICD_REPO }}'
              tag: '{{ trunc 7 .CICD_COMMIT_SHA }}'
          ingress:
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/redirect-permanent: "true"
              traefik.ingress.kubernetes.io/redirect-regex: ^http://(.*)
              traefik.ingress.kubernetes.io/redirect-replacement: https://$1
            hosts:
            - app-{{.CICD_REPO_NAME}}.{{.CLUSTER_NAME}}.{{.ORG_NAME}}.{{.DOMAIN_NAME}}
        mongodb:
          existingSecret: '{{ .CICD_REPO_NAME }}-mongodb'
          metrics:
            enabled: true
          mongodbDatabase: node-application
          replicaSet:
            enabled: true
      wait: true
    image: banzaicloud/ci-pipeline-client:0.8
    when:
      branch:
        include:
        - master
